import { useMemo, useState } from "react";
import { ArrowDown, ArrowUp, ArrowUpRight, BellRing, ChevronRight, Eye, Flame, Heart, MessageCircle, Radio, Share2, Sparkles, TrendingUp } from "lucide-react";
import { Area, AreaChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { conversation, emerging, highlights, kpis, mentions, officialContents, platforms, sentiment, topics } from "@/mocks/dashboard";
import type { Platform, Sentiment } from "@/types/dashboard";

const panel = "rounded-lg border bg-card shadow-[0_1px_2px_color-mix(in_oklab,var(--foreground)_5%,transparent)]";
const sentimentClasses: Record<Sentiment, string> = { Positivo: "bg-emerald-50 text-emerald-700", Neutro: "bg-slate-100 text-slate-600", Negativo: "bg-rose-50 text-rose-700" };
const number = new Intl.NumberFormat("pt-BR");

function SectionTitle({ title, subtitle, action }: { title: string; subtitle?: string; action?: React.ReactNode }) { return <div className="grid grid-cols-[minmax(0,1fr)_auto] items-start gap-3 border-b px-5 py-4"><div className="min-w-0"><h2 className="truncate text-sm font-bold text-foreground">{title}</h2>{subtitle && <p className="mt-0.5 text-xs text-muted-foreground">{subtitle}</p>}</div>{action}</div>; }

function ConversationTooltip({ active, payload }: { active?: boolean; payload?: Array<{ payload: (typeof conversation)[number] }> }) { const item = payload?.[0]?.payload; if (!active || !item) return null; return <div className="rounded-md border bg-popover p-3 text-xs shadow-lg"><p className="font-bold">{item.time} · {item.mentions} menções</p><p className={item.variation >= 0 ? "mt-1 text-emerald-600" : "mt-1 text-destructive"}>{item.variation > 0 ? "+" : ""}{item.variation}% vs. hora anterior</p><p className="mt-2 text-muted-foreground">Assunto principal</p><p className="font-medium">{item.topic}</p></div>; }

export function OverviewDashboard({ platform }: { platform: Platform }) {
  const [mentionPlatform, setMentionPlatform] = useState<Platform>("Todas");
  const [mentionSentiment, setMentionSentiment] = useState<Sentiment | "Todos">("Todos");
  const [topic, setTopic] = useState("Todos");
  const [sort, setSort] = useState("recent");
  const filtered = useMemo(() => mentions.filter((m) => (mentionPlatform === "Todas" || m.platform === mentionPlatform) && (mentionSentiment === "Todos" || m.sentiment === mentionSentiment) && (topic === "Todos" || m.topic === topic)).sort((a,b) => sort === "impact" ? b.interactions - a.interactions : a.id - b.id), [mentionPlatform, mentionSentiment, topic, sort]);

  return <div className="mx-auto max-w-[1600px] space-y-5">
    <div className="grid grid-cols-[minmax(0,1fr)_auto] items-end gap-4"><div><p className="text-xs font-semibold uppercase text-primary">Painel executivo · {platform}</p><h1 className="mt-1 text-2xl font-extrabold sm:text-3xl">81ª SOEA</h1><p className="mt-1 text-sm text-muted-foreground">Visão consolidada das conversas digitais em Sergipe</p></div><div className="hidden items-center gap-2 rounded-md border border-primary/25 bg-primary/5 px-3 py-2 text-xs text-muted-foreground sm:flex"><Radio className="h-4 w-4 text-primary" />Monitoramento ativo</div></div>

    <section className="grid grid-cols-2 gap-3 xl:grid-cols-6">{kpis.map((kpi) => <article key={kpi.label} className={`${panel} min-w-0 p-4`}><div className="flex items-center justify-between gap-2"><p className="truncate text-xs font-semibold text-muted-foreground">{kpi.label}</p><span className={`h-2 w-2 shrink-0 rounded-full ${kpi.tone === "green" ? "bg-emerald-500" : kpi.tone === "red" ? "bg-rose-500" : kpi.tone === "amber" ? "bg-amber-500" : "bg-sky-500"}`} /></div><div className="mt-3 flex flex-wrap items-baseline gap-2"><strong className="text-2xl font-extrabold tabular-nums">{kpi.value}</strong>{kpi.change && <span className={`text-xs font-bold ${kpi.change.startsWith("-") && kpi.label !== "Sentimento negativo" ? "text-destructive" : "text-emerald-600"}`}>{kpi.change}</span>}</div><p className="mt-1 min-h-8 text-[11px] leading-4 text-muted-foreground">{kpi.detail}</p></article>)}</section>

    <section className="grid gap-5 xl:grid-cols-[minmax(0,2fr)_minmax(300px,0.8fr)]">
      <article className={panel}><SectionTitle title="Evolução das conversas" subtitle="Volume de menções ao longo do tempo" action={<span className="text-xs font-semibold text-emerald-600">+24% no período</span>} /><div className="h-80 p-4"><ResponsiveContainer width="100%" height="100%"><AreaChart data={conversation} margin={{ top: 12, right: 8, left: -22, bottom: 0 }}><defs><linearGradient id="mentionsFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="var(--primary)" stopOpacity={0.28}/><stop offset="100%" stopColor="var(--primary)" stopOpacity={0.02}/></linearGradient></defs><CartesianGrid stroke="var(--border)" vertical={false} strokeDasharray="3 3"/><XAxis dataKey="time" axisLine={false} tickLine={false} tick={{ fill: "var(--muted-foreground)", fontSize: 11 }}/><YAxis axisLine={false} tickLine={false} tick={{ fill: "var(--muted-foreground)", fontSize: 11 }}/><Tooltip content={<ConversationTooltip />} cursor={{ stroke: "var(--primary)", strokeDasharray: "4 4" }}/><Area type="monotone" dataKey="mentions" stroke="var(--primary)" strokeWidth={2.5} fill="url(#mentionsFill)" activeDot={{ r: 5, fill: "var(--primary)", stroke: "var(--card)", strokeWidth: 3 }}/></AreaChart></ResponsiveContainer></div></article>
      <article className={panel}><SectionTitle title="Distribuição de sentimento" subtitle="Percepção das conversas analisadas" /><div className="grid grid-cols-[140px_1fr] items-center gap-2 p-5"><div className="relative h-36"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={sentiment} dataKey="value" innerRadius={45} outerRadius={64} paddingAngle={3} stroke="none">{["oklch(0.66 0.15 155)", "oklch(0.72 0.03 240)", "oklch(0.63 0.22 25)"].map((color) => <Cell key={color} fill={color}/>)}</Pie></PieChart></ResponsiveContainer><div className="absolute inset-0 flex flex-col items-center justify-center"><strong className="text-2xl">72%</strong><span className="text-[10px] text-muted-foreground">positivo</span></div></div><div className="space-y-3">{sentiment.map((s, i) => <div key={s.name} className="grid grid-cols-[auto_1fr_auto] items-center gap-2 text-xs"><span className={`h-2 w-2 rounded-full ${i === 0 ? "bg-emerald-500" : i === 1 ? "bg-slate-400" : "bg-rose-500"}`} /><span>{s.name} <strong>{s.value}%</strong></span><span className={i === 0 ? "text-emerald-600" : "text-muted-foreground"}>{s.change}</span></div>)}</div></div><div className="mx-5 mb-5 rounded-md bg-muted p-3 text-xs text-muted-foreground"><strong className="text-foreground">Leitura:</strong> percepção positiva avançou 4 p.p., enquanto a negativa recuou 2 p.p.</div></article>
    </section>

    <section className="grid gap-5 lg:grid-cols-2 xl:grid-cols-3">
      <article className={panel}><SectionTitle title="Assuntos do momento" subtitle="Ranking por volume de menções" /> <div className="divide-y">{topics.map((t,i) => <div key={t.name} className="grid grid-cols-[24px_minmax(0,1fr)_auto] items-center gap-3 px-5 py-3"><span className="text-xs font-bold text-muted-foreground">{i+1}</span><div className="min-w-0"><p className="truncate text-sm font-semibold">{t.name}</p><p className="text-xs text-muted-foreground">{number.format(t.volume)} menções</p></div><div className={`flex items-center gap-1 text-xs font-semibold ${t.change > 5 ? "text-emerald-600" : t.change < 0 ? "text-destructive" : "text-muted-foreground"}`}>{t.change > 5 ? <ArrowUp/> : t.change < 0 ? <ArrowDown/> : <span>→</span>}{Math.abs(t.change)}%</div></div>)}</div></article>
      <article className={panel}><SectionTitle title="Temas emergentes" subtitle="Crescimento acelerado nas últimas 3 horas" /> <div className="space-y-3 p-5">{emerging.map((item, i) => <div key={item.name} className="flex items-center gap-4 rounded-md border bg-background p-4"><div className={`grid h-10 w-10 shrink-0 place-items-center rounded-md ${i === 0 ? "bg-amber-100 text-amber-700" : "bg-accent text-primary"}`}><Sparkles className="h-5 w-5" /></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{item.name}</p><p className="text-xs text-muted-foreground">crescimento nas conversas</p></div><span className="text-sm font-extrabold text-emerald-600">+{item.change}%</span></div>)}</div></article>
      <article className={`${panel} lg:col-span-2 xl:col-span-1`}><SectionTitle title="Onde estão falando" subtitle="Distribuição por plataforma" /><div className="space-y-3 p-5">{platforms.map((p) => <div key={p.name}><div className="mb-1.5 flex justify-between text-xs"><span className="font-medium">{p.name}</span><strong>{p.value}%</strong></div><div className="h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{ width: `${p.value}%` }} /></div></div>)}</div></article>
    </section>

    <section className="grid gap-5 xl:grid-cols-[minmax(0,1.45fr)_minmax(320px,0.7fr)]">
      <article className={panel}><SectionTitle title="Últimas menções" subtitle="Feed consolidado de social listening" />
        <div className="flex gap-2 overflow-x-auto border-b p-3"><Select value={mentionPlatform} onValueChange={(v) => setMentionPlatform(v as Platform)}><SelectTrigger className="w-32 shrink-0"><SelectValue /></SelectTrigger><SelectContent>{["Todas", "Instagram", "X", "Facebook", "YouTube", "LinkedIn", "Notícias"].map(p => <SelectItem key={p} value={p}>{p}</SelectItem>)}</SelectContent></Select><Select value={mentionSentiment} onValueChange={(v) => setMentionSentiment(v as Sentiment | "Todos")}><SelectTrigger className="w-32 shrink-0"><SelectValue /></SelectTrigger><SelectContent>{["Todos", "Positivo", "Neutro", "Negativo"].map(p => <SelectItem key={p} value={p}>{p}</SelectItem>)}</SelectContent></Select><Select value={topic} onValueChange={setTopic}><SelectTrigger className="w-44 shrink-0"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="Todos">Todos os assuntos</SelectItem>{topics.map(t => <SelectItem key={t.name} value={t.name}>{t.name}</SelectItem>)}</SelectContent></Select><Select value={sort} onValueChange={setSort}><SelectTrigger className="ml-auto w-44 shrink-0"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="recent">Mais recentes</SelectItem><SelectItem value="impact">Maior repercussão</SelectItem></SelectContent></Select></div>
        <div className="divide-y">{filtered.length ? filtered.map(m => <div key={m.id} className="p-5"><div className="grid grid-cols-[auto_minmax(0,1fr)_auto] gap-3"><div className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-accent text-xs font-bold text-primary">{m.initials}</div><div className="min-w-0"><div className="flex flex-wrap items-center gap-x-2 gap-y-1"><span className="text-sm font-bold">{m.author}</span><span className="text-xs text-muted-foreground">{m.handle}</span><span className="rounded bg-muted px-1.5 py-0.5 text-[10px] font-semibold">{m.platform}</span><span className="text-[10px] text-muted-foreground">{m.time}</span></div><p className="mt-2 text-sm leading-6 text-foreground/85">{m.text}</p><div className="mt-3 flex flex-wrap items-center gap-3"><span className={`rounded px-2 py-1 text-[10px] font-semibold ${sentimentClasses[m.sentiment]}`}>{m.sentiment}</span><span className="flex items-center gap-1 text-xs text-muted-foreground"><Heart className="h-3.5 w-3.5" />{m.interactions}</span><span className="text-xs text-muted-foreground">{m.topic}</span></div></div><Button variant="ghost" size="icon" aria-label="Ver publicação"><ArrowUpRight /></Button></div></div>) : <p className="p-8 text-center text-sm text-muted-foreground">Nenhuma menção corresponde aos filtros selecionados.</p>}</div>
      </article>
      <div className="space-y-5"><article className={panel}><SectionTitle title="Picos de conversa" subtitle="Momentos-chave do dia" /> <div className="space-y-5 p-5">{[{time:"14h32",count:"468 menções",topic:"Inteligência Artificial",change:"+280%"},{time:"11h15",count:"312 menções",topic:"Abertura da SOEA",change:"+164%"},{time:"09h48",count:"246 menções",topic:"Engenharia sustentável",change:"+92%"}].map((p,i) => <div key={p.time} className="grid grid-cols-[auto_1fr_auto] gap-3"><div className={`grid h-9 w-9 place-items-center rounded-md ${i === 0 ? "bg-amber-100 text-amber-700" : "bg-accent text-primary"}`}><Flame className="h-4 w-4" /></div><div><p className="text-xs font-bold">{p.time} · {p.count}</p><p className="mt-1 text-xs text-muted-foreground">{p.topic}</p></div><strong className="text-xs text-emerald-600">{p.change}</strong></div>)}</div></article>
        <article className={panel}><SectionTitle title="Alertas de monitoramento" subtitle="Ocorrências que exigem atenção" /><div className="divide-y">{[{icon:Flame,title:"Pico de conversa",text:"IA cresce 280% desde 14h32",tone:"text-amber-600"},{icon:BellRing,title:"Sentimento negativo",text:"Alta pontual sobre acesso ao evento",tone:"text-rose-600"},{icon:TrendingUp,title:"Novo tema em crescimento",text:"Mobilidade urbana avança 184%",tone:"text-primary"},{icon:Eye,title:"Conteúdo em destaque",text:"Reel de abertura supera 186 mil views",tone:"text-emerald-600"}].map(a => <div key={a.title} className="flex gap-3 p-4"><a.icon className={`mt-0.5 h-4 w-4 shrink-0 ${a.tone}`} /><div><p className="text-xs font-bold">{a.title}</p><p className="mt-1 text-xs text-muted-foreground">{a.text}</p></div></div>)}</div></article></div>
    </section>

    <section className="grid gap-5 xl:grid-cols-[minmax(0,1.45fr)_minmax(320px,0.7fr)]">
      <article className={panel}><SectionTitle title="Conteúdos oficiais" subtitle="Performance agregada · estrutura Zeeng ready" action={<Button variant="ghost" size="sm">Ver todos <ChevronRight /></Button>} /><div className="grid grid-cols-2 gap-px bg-border sm:grid-cols-5">{[{l:"Visualizações",v:"540,5 mil"},{l:"Alcance",v:"412,8 mil"},{l:"Interações",v:"36,8 mil"},{l:"Engajamento",v:"6,8%"},{l:"Compartilhamentos",v:"8.430"}].map(x => <div key={x.l} className="bg-card p-4"><p className="text-[10px] uppercase text-muted-foreground">{x.l}</p><p className="mt-1 text-lg font-extrabold">{x.v}</p></div>)}</div><div className="divide-y">{officialContents.map((c,i) => <div key={c.title} className="grid grid-cols-[22px_minmax(0,1fr)_auto] items-center gap-3 px-5 py-3"><span className="text-xs font-bold text-muted-foreground">{i+1}</span><div className="min-w-0"><p className="truncate text-sm font-semibold">{c.title}</p><p className="text-xs text-muted-foreground">{c.type} · {number.format(c.views)} visualizações</p></div><div className="text-right"><p className="text-xs font-bold">{number.format(c.interactions)}</p><p className="text-[10px] text-muted-foreground">{c.engagement} eng.</p></div></div>)}</div></article>
      <article className={panel}><SectionTitle title="Impacto da comunicação" subtitle="Conteúdo oficial vs. conversa espontânea" /><div className="p-5"><div className="rounded-md bg-primary p-5 text-primary-foreground"><p className="text-xs font-semibold opacity-80">PUBLICAÇÃO DE MAIOR IMPACTO</p><h3 className="mt-2 text-base font-bold">Reel · IA na Engenharia</h3><div className="mt-5 flex items-end justify-between"><div><strong className="text-3xl">+218%</strong><p className="mt-1 text-xs opacity-80">menções espontâneas após a publicação</p></div><TrendingUp className="h-8 w-8 opacity-70" /></div></div><div className="mt-5 space-y-3">{[{l:"Tempo até o pico",v:"27 min"},{l:"Novos autores",v:"1.284"},{l:"Sentimento positivo",v:"81%"}].map(x => <div key={x.l} className="flex justify-between border-b pb-3 text-sm"><span className="text-muted-foreground">{x.l}</span><strong>{x.v}</strong></div>)}</div></div></article>
    </section>

    <section><div className="mb-3 flex items-center justify-between"><div><h2 className="text-sm font-bold">Menções em destaque</h2><p className="text-xs text-muted-foreground">Publicações com maior repercussão</p></div></div><div className="grid gap-3 md:grid-cols-3">{highlights.map(h => <article key={h.author} className={`${panel} p-5`}><div className="flex items-center justify-between"><div><p className="text-sm font-bold">{h.author}</p><p className="text-xs text-muted-foreground">{h.platform}</p></div><span className={`rounded px-2 py-1 text-[10px] font-semibold ${sentimentClasses[h.sentiment]}`}>{h.sentiment}</span></div><p className="my-4 text-sm leading-6">“{h.excerpt}”</p><div className="grid grid-cols-3 gap-2 border-t pt-4 text-center"><div><Eye className="mx-auto h-3.5 w-3.5 text-muted-foreground"/><strong className="mt-1 block text-xs">{h.reach}</strong><span className="text-[9px] text-muted-foreground">alcance</span></div><div><MessageCircle className="mx-auto h-3.5 w-3.5 text-muted-foreground"/><strong className="mt-1 block text-xs">{h.interactions}</strong><span className="text-[9px] text-muted-foreground">interações</span></div><div><Share2 className="mx-auto h-3.5 w-3.5 text-muted-foreground"/><strong className="mt-1 block text-xs">{h.shares}</strong><span className="text-[9px] text-muted-foreground">compart.</span></div></div></article>)}</div></section>

    <footer className={`${panel} grid gap-4 border-t-2 border-t-primary/50 p-5 sm:grid-cols-[minmax(0,1fr)_auto] sm:items-center`}><div><h2 className="text-sm font-bold">Status das fontes e integrações</h2><p className="mt-1 text-xs text-muted-foreground">Infraestrutura pronta para evolução das conexões</p></div><div className="flex flex-wrap gap-x-5 gap-y-2 text-xs"><span><i className="mr-1.5 inline-block h-2 w-2 rounded-full bg-emerald-500"/>V-Tracker · Estrutura preparada</span><span><i className="mr-1.5 inline-block h-2 w-2 rounded-full bg-primary"/>Zeeng · Integração futura</span><span><i className="mr-1.5 inline-block h-2 w-2 rounded-full bg-primary"/>Lovable Cloud · Conexão futura</span><span className="text-muted-foreground">Última sincronização: 14:45</span></div></footer>
  </div>;
}